spring:
  application:
    name: coordinator
  data:
    mongodb:
      uri: mongodb://localhost:27017/coordinator_db
  
server:
  port: 8002
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.bank.coordinator: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always
